# version: '3'

# services:
#   restaurent-mng-bc:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8080:8080"
#     depends_on:
#       - mongodb
#       - redis

#   mongodb:
#     image: mongo
#     ports:
#       - "27017:27017"

#   redis:
#     image: redis
#     ports:
#       - "6479:6379"


version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6479:6379"
